# Generated by Django 2.1.5 on 2019-01-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NearBeachAPI', '0002_api_uuid_api_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_uuid',
            name='api_description',
            field=models.CharField(default='Happy', max_length=255),
            preserve_default=False,
        ),
    ]
